#!/bin/bash
set -e

# Installation script for Astrometry.net solve-field and index files
# Downloads index files covering typical astrophotography FOVs (0.4° to 30°)

ASTROMETRY_DATA_DIR=${ASTROMETRY_DATA_DIR:-/usr/local/astrometry/data}
INDEX_BASE_URL="http://data.astrometry.net/4100"

echo "Installing Astrometry.net solve-field and index files..."
echo "Data directory: $ASTROMETRY_DATA_DIR"
echo ""

# Check if solve-field is installed
if ! command -v solve-field &> /dev/null; then
    echo "ERROR: solve-field command not found!"
    echo "Please install astrometry.net first:"
    echo "  Ubuntu/Debian: sudo apt-get install astrometry.net"
    echo "  Fedora: sudo dnf install astrometry"
    echo "  Arch: sudo pacman -S astrometry.net"
    echo "  macOS: brew install astrometry-net"
    exit 1
fi

echo "✓ solve-field found at: $(which solve-field)"
echo ""

# Create data directory if it doesn't exist
mkdir -p "$ASTROMETRY_DATA_DIR"

# Download index files 4107-4113 (~350MB total)
# These cover FOVs from ~0.4° to ~30°, suitable for DSLR/CCD astrophotography
# Scale 7 (4107): 0.4-0.75° - wide-field (short focal lengths)
# Scale 8 (4108): 0.5-1.1° - wide-field
# Scale 9 (4109): 1.1-2.1° - medium-wide
# Scale 10 (4110): 2-4° - medium
# Scale 11 (4111): 4-8° - medium-narrow
# Scale 12 (4112): 8-16° - narrow (long focal lengths)
# Scale 13 (4113): 16-30° - very narrow
echo "Downloading index files (index-4107 to index-4113, ~350MB total)..."
echo "This may take a few minutes depending on your connection..."
echo ""

for i in {4107..4113}; do
    INDEX_FILE="index-${i}.fits"
    INDEX_PATH="$ASTROMETRY_DATA_DIR/$INDEX_FILE"
    
    if [ -f "$INDEX_PATH" ]; then
        echo "  ✓ $INDEX_FILE already exists, skipping"
    else
        echo "  Downloading $INDEX_FILE..."
        if wget --show-progress -O "$INDEX_PATH" "$INDEX_BASE_URL/$INDEX_FILE" 2>&1; then
            echo "  ✓ $INDEX_FILE downloaded"
        else
            echo "  ✗ Failed to download $INDEX_FILE"
            rm -f "$INDEX_PATH"
            exit 1
        fi
    fi
done

echo ""
echo "Creating configuration file..."

# Create astrometry.cfg if it doesn't exist
CONFIG_FILE="/etc/astrometry.cfg"
if [ ! -f "$CONFIG_FILE" ]; then
    cat > "$CONFIG_FILE" <<EOF
# Astrometry.net configuration
# Generated by install-solve-field.sh

# Add the index file directory
add_path $ASTROMETRY_DATA_DIR

# Don't use built-in indices from other locations
autoindex

# Increase memory limit for large images (MB)
minwidth 10

# Disable unnecessary features for speed
inparallel
EOF
    echo "✓ Created $CONFIG_FILE"
else
    echo "✓ $CONFIG_FILE already exists"
    # Check if our data directory is in the config
    if ! grep -q "$ASTROMETRY_DATA_DIR" "$CONFIG_FILE"; then
        echo "⚠ Warning: $ASTROMETRY_DATA_DIR is not in $CONFIG_FILE"
        echo "  Add this line to your config: add_path $ASTROMETRY_DATA_DIR"
    fi
fi

echo ""
echo "Installation complete!"
echo ""
echo "Index files installed to: $ASTROMETRY_DATA_DIR"
echo "Configuration file: $CONFIG_FILE"
echo ""
echo "Testing installation..."
solve-field --help > /dev/null && echo "✓ solve-field is working"
echo ""
echo "You can now use solve-field for local plate solving."
echo "In the app Settings, set the Astrometry.net data directory to: $ASTROMETRY_DATA_DIR"
